### PR TITLE
update nx to 19.1 with Angular 18

### PR DESCRIPTION
**Pull request by Markus-Ende**

### CODE REVIEW

**Comment by Markus-Ende** [comment]
@Romanchuk wanted to help, but possibly causing more work by this PR? Don't know why I have conflicts, should I try to solve them, or do you want to update by yourself?

**Comment by Romanchuk** [comment]
Thanks, but i need to do much more. Including realising other libs on which angular-i18next-demo is dependent.
I have to do it by myself. Appreciate job you did!

**Comment by Romanchuk** [comment]
@Markus-Ende It will be too much work for you. I'm doing it right now) Thank again

**Comment by Romanchuk** [comment]
@Markus-Ende 
`angular-i18next 18.0.0 published 🎉`

**Pull request closed without merging**
