### PR TITLE
Update to last i18next version and Angular v-17

### LINKED ISSUE #113: Update to last i18next version
in project package json you have this peerDependencies:
``` 
"peerDependencies": {
    "@angular/common": ">=16.0.0 <17.0.0",
    "@angular/core": ">=16.0.0 <17.0.0",
    "@angular/platform-browser": ">=16.0.0 <17.0.0",
    "i18next": ">=22.0.8 <23.0.0",
    "rxjs": ">=6.6.0 <8.0.0"
  },
```

 current version of i18next is 23.5.1

### PR DESCRIPTION
**Pull request by luca-peruzzo**
closes #113

### CODE REVIEW

**Comment by JacobF7** [comment]
@Romanchuk - do you think we'll get this Merged anytime soon. It's currently blocking our upgrade to the latest Angular

**Comment by MathiasWasAlreadyTaken** [comment]
Looking at his recent activity on Github (last update in June), I would suggest we create a fork from this and use that instead.
He might even been drafted to the war...

**Comment by Romanchuk** [comment]
@MathiasWasAlreadyTaken Do you think i can't merge it while in frontline?

**Comment by Romanchuk** [comment]
https://www.npmjs.com/package/angular-i18next/v/17.0.0-0

**Comment by MathiasWasAlreadyTaken** [comment]
The change in the file libs/angular-i18next/src/lib/models.ts made it worse for us.
https://github.com/Romanchuk/angular-i18next/blob/82b33a833af6dd038064ff60975653308a878d88/libs/angular-i18next/src/lib/models.ts#L8
It can't transform with a string array anymore.
If a string to be transformed look like this `"Send from {{0}} to {{1}}."`, you could transform with a string array of two items.
```
const values[];
values.push("Earth");
values.push("Moon");
this.i18NextPipe.transform('string-key', values);
```
Now it only takes a dictionary as parameter.

**Comment by luca-peruzzo** [comment]
> "Send from {{0}} to {{1}}."

@Romanchuk 

maybe we could typing TOptions like that:

image

**Comment by MathiasWasAlreadyTaken** [comment]
I read about the breaking change in the latest i18next migration guide.
I try and get some time over during the day to test your change, and post the result here.

**Comment by Romanchuk** [comment]
I did fix types that changed in i18next.

https://github.com/Romanchuk/angular-i18next/releases/tag/v17.0.0-1

https://www.npmjs.com/package/angular-i18next/v/17.0.0-1

@MathiasWasAlreadyTaken 

```
const values[];
values.push("Earth");
values.push("Moon");
this.i18NextPipe.transform('string-key', values);
```

It won't fix your problem. With previous types PipeOptions actualy detected by typescript as 'any'. But it **meant to be an object** (by i18next). i18next can interpolate any key in options object. It did work because array also has access by a key. But i18next doesn't really expect an array to be passed as options. We have to stick to an i18next typings

If you want numbers this should work for you:
```
{
"1": "Earth",
"2": "Moon"
}
```
or
const values = {};
values[0]="Earth";
values[1]="Moon";

**Comment by Romanchuk** [comment]
@luca-peruzzo Plz, let me know if 17.0.0-1 is OK for you

**Comment by luca-peruzzo** [comment]
> @luca-peruzzo Plz, let me know if 17.0.0-1 is OK for you

Yep, in my project I always use object interpolation when needed, so no issues for me

**Comment by Romanchuk** [comment]
I'll release stable version tomorrow

**Pull request merged**
